In [1]:
import pandas as pd
import numpy as np

In [2]:
game_desc = pd.read_csv("descriptions.csv")

In [42]:
game_desc.head(20)

gameid                                        description
0    30549  [In Pandemic, several virulent diseases have b...
1      822  [Carcassonne is a tile-placement game in which...
2       13  [In Catan (formerly The Settlers of Catan), pl...
3    68448  [You are the leader of one of the 7 great citi...
4    36218  [&amp;quot;You are a monarch, like your parent...
5     9209  [With elegantly simple gameplay, Ticket to Rid...
6   178900  [Two rival spymasters know the secret identiti...
7    31260  [Description from BoardgameNews&amp;#10;&amp;#...
8     3076  [In Puerto Rico players assume the roles of co...
9    40692  [In Small World, players vie for conquest and ...
10  167791  [In the 2400s, mankind begins to terraform the...
11   70323  [In King of Tokyo, you play mutant monsters, g...
12   14996  [Ticket to Ride: Europe takes you on a new tra...
13  148228  [Splendor is a game of chip-collecting and car...
14    2651  [Power Grid is the updated release of the Frie...
15  173346  [In many ways 7 Wonders Duel resembles its par...
16  129622  [All of the eligible young men (and many of th...
17  169786  [It is a time of unrest in 1920s Europa. The a...
18   39856  [2010 Spiel des Jahres Winner&amp;#10;&amp;#10...
19     478  [In Citadels, players take on new roles each r...

In [31]:
game_31260 = game_desc.loc[game_desc['gameid'] == 31260]
game_31260

gameid                                        description
7   31260  [Description from BoardgameNews&amp;#10;&amp;#...

In [32]:
game_31260.values

array([[31260,
        "[Description from BoardgameNews&amp;#10;&amp;#10;In Agricola, you're a farmer in a wooden shack with your spouse and little else. On a turn, you get to take only two actions, one for you and one for the spouse, from all the possibilities you'll find on a farm: collecting clay, wood, or stone; building fences; and so on. You might think about having kids in order to get more work accomplished, but first you need to expand your house. And what are you going to feed all the little rugrats?&amp;#10;&amp;#10;The game supports many levels of complexity, mainly through the use (or non-use) of two of its main types of cards, Minor Improvements and Occupations. In the beginner's version (called the Family Variant in the U.S. release), these cards are not used at all. For advanced play, the U.S. release includes three levels of both types of cards; Basic (E-deck), Interactive (I-deck), and Complex (K-deck), and the rulebook encourages players to experiment with the variou

In [33]:
game_31260['description'] = game_31260['description'].str.replace('&amp;#10;','')

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [34]:
game_31260.values

array([[31260,
        "[Description from BoardgameNewsIn Agricola, you're a farmer in a wooden shack with your spouse and little else. On a turn, you get to take only two actions, one for you and one for the spouse, from all the possibilities you'll find on a farm: collecting clay, wood, or stone; building fences; and so on. You might think about having kids in order to get more work accomplished, but first you need to expand your house. And what are you going to feed all the little rugrats?The game supports many levels of complexity, mainly through the use (or non-use) of two of its main types of cards, Minor Improvements and Occupations. In the beginner's version (called the Family Variant in the U.S. release), these cards are not used at all. For advanced play, the U.S. release includes three levels of both types of cards; Basic (E-deck), Interactive (I-deck), and Complex (K-deck), and the rulebook encourages players to experiment with the various decks and mixtures thereof. Afterm

In [35]:
game_31260['description'] = game_31260['description'].str.replace(r'[^\w\s]+', '')

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [36]:
game_31260.values

array([[31260,
        'Description from BoardgameNewsIn Agricola youre a farmer in a wooden shack with your spouse and little else On a turn you get to take only two actions one for you and one for the spouse from all the possibilities youll find on a farm collecting clay wood or stone building fences and so on You might think about having kids in order to get more work accomplished but first you need to expand your house And what are you going to feed all the little rugratsThe game supports many levels of complexity mainly through the use or nonuse of two of its main types of cards Minor Improvements and Occupations In the beginners version called the Family Variant in the US release these cards are not used at all For advanced play the US release includes three levels of both types of cards Basic Edeck Interactive Ideck and Complex Kdeck and the rulebook encourages players to experiment with the various decks and mixtures thereof Aftermarket decks such as the ZDeck and the LDeck als

In [37]:
game_31260['description'] = game_31260['description'].str.replace(r'\d+', '')

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [38]:
game_31260.values

array([[31260,
        'Description from BoardgameNewsIn Agricola youre a farmer in a wooden shack with your spouse and little else On a turn you get to take only two actions one for you and one for the spouse from all the possibilities youll find on a farm collecting clay wood or stone building fences and so on You might think about having kids in order to get more work accomplished but first you need to expand your house And what are you going to feed all the little rugratsThe game supports many levels of complexity mainly through the use or nonuse of two of its main types of cards Minor Improvements and Occupations In the beginners version called the Family Variant in the US release these cards are not used at all For advanced play the US release includes three levels of both types of cards Basic Edeck Interactive Ideck and Complex Kdeck and the rulebook encourages players to experiment with the various decks and mixtures thereof Aftermarket decks such as the ZDeck and the LDeck als

In [40]:
game_31260['description'] = game_31260['description'].str.lower()

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [41]:
game_31260.values

array([[31260,
        'description from boardgamenewsin agricola youre a farmer in a wooden shack with your spouse and little else on a turn you get to take only two actions one for you and one for the spouse from all the possibilities youll find on a farm collecting clay wood or stone building fences and so on you might think about having kids in order to get more work accomplished but first you need to expand your house and what are you going to feed all the little rugratsthe game supports many levels of complexity mainly through the use or nonuse of two of its main types of cards minor improvements and occupations in the beginners version called the family variant in the us release these cards are not used at all for advanced play the us release includes three levels of both types of cards basic edeck interactive ideck and complex kdeck and the rulebook encourages players to experiment with the various decks and mixtures thereof aftermarket decks such as the zdeck and the ldeck als

In [43]:
game_desc['description'] = game_desc['description'].str.replace('&amp;#10;','')
game_desc['description'] = game_desc['description'].str.replace(r'[^\w\s]+', '')
game_desc['description'] = game_desc['description'].str.replace(r'\d+', '')
game_desc['description'] = game_desc['description'].str.lower()

In [44]:
game_desc.head(20)

gameid                                        description
0    30549  in pandemic several virulent diseases have bro...
1      822  carcassonne is a tileplacement game in which t...
2       13  in catan formerly the settlers of catan player...
3    68448  you are the leader of one of the  great cities...
4    36218  ampquotyou are a monarch like your parents bef...
5     9209  with elegantly simple gameplay ticket to ride ...
6   178900  two rival spymasters know the secret identitie...
7    31260  description from boardgamenewsin agricola your...
8     3076  in puerto rico players assume the roles of col...
9    40692  in small world players vie for conquest and co...
10  167791  in the s mankind begins to terraform the plane...
11   70323  in king of tokyo you play mutant monsters giga...
12   14996  ticket to ride europe takes you on a new train...
13  148228  splendor is a game of chipcollecting and card ...
14    2651  power grid is the updated release of the fried...
15  173346  in many ways  wonders duel resembles its paren...
16  129622  all of the eligible young men and many of the ...
17  169786  it is a time of unrest in s europa the ashes f...
18   39856   spiel des jahres winnerone player is the stor...
19     478  in citadels players take on new roles each rou...

In [45]:
import MySQLdb
from pandas.io import sql
from sqlalchemy import create_engine
engine = create_engine('mysql+mysqldb://root:LolaHippo74@127.0.0.1:3306/board_games?charset=utf8mb4')

In [46]:
games = pd.read_sql("SELECT id, name FROM games", engine)

In [47]:
games.head(20)

id                    name
0    30549                Pandemic
1      822             Carcassonne
2       13                   Catan
3    68448               7 Wonders
4    36218                Dominion
5     9209          Ticket to Ride
6   178900               Codenames
7    31260                Agricola
8     3076             Puerto Rico
9    40692             Small World
10  167791       Terraforming Mars
11   70323           King of Tokyo
12   14996  Ticket to Ride: Europe
13  148228                Splendor
14    2651              Power Grid
15  173346          7 Wonders Duel
16  129622             Love Letter
17  169786                  Scythe
18   39856                   Dixit
19     478                Citadels

In [48]:
game_desc.columns = ['id', 'description']

In [49]:
game_desc.head()

id                                        description
0  30549  in pandemic several virulent diseases have bro...
1    822  carcassonne is a tileplacement game in which t...
2     13  in catan formerly the settlers of catan player...
3  68448  you are the leader of one of the  great cities...
4  36218  ampquotyou are a monarch like your parents bef...

In [50]:
game_plus_desc_df = pd.merge(games, game_desc, how="left", on="id")

In [51]:
game_plus_desc_df.head()

id         name                                        description
0  30549     Pandemic  in pandemic several virulent diseases have bro...
1    822  Carcassonne  carcassonne is a tileplacement game in which t...
2     13        Catan  in catan formerly the settlers of catan player...
3  68448    7 Wonders  you are the leader of one of the  great cities...
4  36218     Dominion  ampquotyou are a monarch like your parents bef...