In [1]:
import pandas as pd
import numpy as np

In [2]:
game_desc = pd.read_csv("descriptions.csv")

In [3]:
game_desc.head(20)

gameid                                        description
0    30549  [In Pandemic, several virulent diseases have b...
1      822  [Carcassonne is a tile-placement game in which...
2       13  [In Catan (formerly The Settlers of Catan), pl...
3    68448  [You are the leader of one of the 7 great citi...
4    36218  [&amp;quot;You are a monarch, like your parent...
5     9209  [With elegantly simple gameplay, Ticket to Rid...
6   178900  [Two rival spymasters know the secret identiti...
7    31260  [Description from BoardgameNews&amp;#10;&amp;#...
8     3076  [In Puerto Rico players assume the roles of co...
9    40692  [In Small World, players vie for conquest and ...
10  167791  [In the 2400s, mankind begins to terraform the...
11   70323  [In King of Tokyo, you play mutant monsters, g...
12   14996  [Ticket to Ride: Europe takes you on a new tra...
13  148228  [Splendor is a game of chip-collecting and car...
14    2651  [Power Grid is the updated release of the Frie...
15  173346  [In many ways 7 Wonders Duel resembles its par...
16  129622  [All of the eligible young men (and many of th...
17  169786  [It is a time of unrest in 1920s Europa. The a...
18   39856  [2010 Spiel des Jahres Winner&amp;#10;&amp;#10...
19     478  [In Citadels, players take on new roles each r...

In [31]:
game_31260 = game_desc.loc[game_desc['gameid'] == 31260]
game_31260

gameid                                        description
7   31260  [Description from BoardgameNews&amp;#10;&amp;#...

In [32]:
game_31260.values

array([[31260,
        "[Description from BoardgameNews&amp;#10;&amp;#10;In Agricola, you're a farmer in a wooden shack with your spouse and little else. On a turn, you get to take only two actions, one for you and one for the spouse, from all the possibilities you'll find on a farm: collecting clay, wood, or stone; building fences; and so on. You might think about having kids in order to get more work accomplished, but first you need to expand your house. And what are you going to feed all the little rugrats?&amp;#10;&amp;#10;The game supports many levels of complexity, mainly through the use (or non-use) of two of its main types of cards, Minor Improvements and Occupations. In the beginner's version (called the Family Variant in the U.S. release), these cards are not used at all. For advanced play, the U.S. release includes three levels of both types of cards; Basic (E-deck), Interactive (I-deck), and Complex (K-deck), and the rulebook encourages players to experiment with the variou

In [33]:
game_31260['description'] = game_31260['description'].str.replace('&amp;#10;','')

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [34]:
game_31260.values

array([[31260,
        "[Description from BoardgameNewsIn Agricola, you're a farmer in a wooden shack with your spouse and little else. On a turn, you get to take only two actions, one for you and one for the spouse, from all the possibilities you'll find on a farm: collecting clay, wood, or stone; building fences; and so on. You might think about having kids in order to get more work accomplished, but first you need to expand your house. And what are you going to feed all the little rugrats?The game supports many levels of complexity, mainly through the use (or non-use) of two of its main types of cards, Minor Improvements and Occupations. In the beginner's version (called the Family Variant in the U.S. release), these cards are not used at all. For advanced play, the U.S. release includes three levels of both types of cards; Basic (E-deck), Interactive (I-deck), and Complex (K-deck), and the rulebook encourages players to experiment with the various decks and mixtures thereof. Afterm

In [35]:
game_31260['description'] = game_31260['description'].str.replace(r'[^\w\s]+', '')

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [36]:
game_31260.values

array([[31260,
        'Description from BoardgameNewsIn Agricola youre a farmer in a wooden shack with your spouse and little else On a turn you get to take only two actions one for you and one for the spouse from all the possibilities youll find on a farm collecting clay wood or stone building fences and so on You might think about having kids in order to get more work accomplished but first you need to expand your house And what are you going to feed all the little rugratsThe game supports many levels of complexity mainly through the use or nonuse of two of its main types of cards Minor Improvements and Occupations In the beginners version called the Family Variant in the US release these cards are not used at all For advanced play the US release includes three levels of both types of cards Basic Edeck Interactive Ideck and Complex Kdeck and the rulebook encourages players to experiment with the various decks and mixtures thereof Aftermarket decks such as the ZDeck and the LDeck als

In [37]:
game_31260['description'] = game_31260['description'].str.replace(r'\d+', '')

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [38]:
game_31260.values

array([[31260,
        'Description from BoardgameNewsIn Agricola youre a farmer in a wooden shack with your spouse and little else On a turn you get to take only two actions one for you and one for the spouse from all the possibilities youll find on a farm collecting clay wood or stone building fences and so on You might think about having kids in order to get more work accomplished but first you need to expand your house And what are you going to feed all the little rugratsThe game supports many levels of complexity mainly through the use or nonuse of two of its main types of cards Minor Improvements and Occupations In the beginners version called the Family Variant in the US release these cards are not used at all For advanced play the US release includes three levels of both types of cards Basic Edeck Interactive Ideck and Complex Kdeck and the rulebook encourages players to experiment with the various decks and mixtures thereof Aftermarket decks such as the ZDeck and the LDeck als

In [40]:
game_31260['description'] = game_31260['description'].str.lower()

C:\Users\timco\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [41]:
game_31260.values

array([[31260,
        'description from boardgamenewsin agricola youre a farmer in a wooden shack with your spouse and little else on a turn you get to take only two actions one for you and one for the spouse from all the possibilities youll find on a farm collecting clay wood or stone building fences and so on you might think about having kids in order to get more work accomplished but first you need to expand your house and what are you going to feed all the little rugratsthe game supports many levels of complexity mainly through the use or nonuse of two of its main types of cards minor improvements and occupations in the beginners version called the family variant in the us release these cards are not used at all for advanced play the us release includes three levels of both types of cards basic edeck interactive ideck and complex kdeck and the rulebook encourages players to experiment with the various decks and mixtures thereof aftermarket decks such as the zdeck and the ldeck als

In [4]:
game_desc['description'] = game_desc['description'].str.replace('&amp;#10;','')
game_desc['description'] = game_desc['description'].str.replace(r'[^\w\s]+', '')
game_desc['description'] = game_desc['description'].str.replace(r'\d+', '')
game_desc['description'] = game_desc['description'].str.lower()

In [5]:
game_desc.head(20)

gameid                                        description
0    30549  in pandemic several virulent diseases have bro...
1      822  carcassonne is a tileplacement game in which t...
2       13  in catan formerly the settlers of catan player...
3    68448  you are the leader of one of the  great cities...
4    36218  ampquotyou are a monarch like your parents bef...
5     9209  with elegantly simple gameplay ticket to ride ...
6   178900  two rival spymasters know the secret identitie...
7    31260  description from boardgamenewsin agricola your...
8     3076  in puerto rico players assume the roles of col...
9    40692  in small world players vie for conquest and co...
10  167791  in the s mankind begins to terraform the plane...
11   70323  in king of tokyo you play mutant monsters giga...
12   14996  ticket to ride europe takes you on a new train...
13  148228  splendor is a game of chipcollecting and card ...
14    2651  power grid is the updated release of the fried...
15  173346  in many ways  wonders duel resembles its paren...
16  129622  all of the eligible young men and many of the ...
17  169786  it is a time of unrest in s europa the ashes f...
18   39856   spiel des jahres winnerone player is the stor...
19     478  in citadels players take on new roles each rou...

In [6]:
import MySQLdb
from pandas.io import sql
from sqlalchemy import create_engine


In [7]:
with open("username.txt") as f:
    user = f.read()
with open("password.txt") as g:
    password = g.read()

In [8]:
engine = create_engine('mysql+mysqldb://' + user + ':' + password + '@127.0.0.1:3306/board_games?charset=utf8mb4')

In [9]:
games = pd.read_sql("SELECT id, name FROM games", engine)

In [10]:
games.head(20)

id                    name
0    30549                Pandemic
1      822             Carcassonne
2       13                   Catan
3    68448               7 Wonders
4    36218                Dominion
5     9209          Ticket to Ride
6   178900               Codenames
7    31260                Agricola
8     3076             Puerto Rico
9    40692             Small World
10  167791       Terraforming Mars
11   70323           King of Tokyo
12   14996  Ticket to Ride: Europe
13  148228                Splendor
14    2651              Power Grid
15  173346          7 Wonders Duel
16  129622             Love Letter
17  169786                  Scythe
18   39856                   Dixit
19     478                Citadels

In [11]:
game_desc.columns = ['id', 'description']

In [12]:
game_desc.head()

id                                        description
0  30549  in pandemic several virulent diseases have bro...
1    822  carcassonne is a tileplacement game in which t...
2     13  in catan formerly the settlers of catan player...
3  68448  you are the leader of one of the  great cities...
4  36218  ampquotyou are a monarch like your parents bef...

In [13]:
game_plus_desc_df = pd.merge(games, game_desc, how="left", on="id")

In [14]:
game_plus_desc_df.head()

id         name                                        description
0  30549     Pandemic  in pandemic several virulent diseases have bro...
1    822  Carcassonne  carcassonne is a tileplacement game in which t...
2     13        Catan  in catan formerly the settlers of catan player...
3  68448    7 Wonders  you are the leader of one of the  great cities...
4  36218     Dominion  ampquotyou are a monarch like your parents bef...

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
game_plus_desc_df['description'] = game_plus_desc_df['description'].fillna('')
tfidf_matrix = tfidf.fit_transform(game_plus_desc_df['description'])
tfidf_matrix.shape

(3000, 35717)

In [16]:
tfidf.get_feature_names()[5000:5010]

['bridgewhoever',
 'brief',
 'briefcase',
 'briefing',
 'briefly',
 'brigade',
 'brigades',
 'brigands',
 'brigandsfor',
 'bright']

In [17]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim.shape

(3000, 3000)

In [18]:
cosine_sim[1]

array([0.01324948, 1.        , 0.05055651, ..., 0.01592518, 0.00440865,
       0.01497063])

In [19]:
indices = pd.Series(game_plus_desc_df.index, index=game_plus_desc_df['name']).drop_duplicates()

In [20]:
indices[:10]

name
Pandemic          0
Carcassonne       1
Catan             2
7 Wonders         3
Dominion          4
Ticket to Ride    5
Codenames         6
Agricola          7
Puerto Rico       8
Small World       9
dtype: int64

In [25]:
def get_recommendations(name, cosine_sim=cosine_sim):
    # Get the index of the game that matches the title
    idx = indices[name]

    # Get the pairwsie similarity scores of all games with that game
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the games based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar games
    sim_scores = sim_scores[1:11]

    # Get the game indices
    game_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar games
    return game_plus_desc_df['name'].iloc[game_indices]

In [26]:
get_recommendations('Ticket to Ride')

681                      Ticket to Ride: 10th Anniversary
739                           Ticket to Ride: Switzerland
12                                 Ticket to Ride: Europe
745                           Ticket to Ride: Europa 1912
318                              Ticket to Ride: USA 1910
666     Ticket to Ride Map Collection: Volume 2 – Indi...
2403                 Ticket to Ride: First Journey (U.S.)
809     Ticket to Ride Map Collection: Volume 5 – Unit...
1253                        Ticket to Ride: Rails & Sails
665     Ticket to Ride Map Collection: Volume 1 – Team...
Name: name, dtype: object

In [27]:
get_recommendations('Harry Potter: Hogwarts Battle')

2211    Harry Potter: Hogwarts Battle – The Monster Bo...
2967                       Harry Potter Trading Card Game
124                Legendary: A Marvel Deck Building Game
1328    Legendary: A Marvel Deck Building Game – Villains
548                          DC Comics Deck-Building Game
425                                     Disney Villainous
1940           DC Comics Deck-Building Game: Heroes Unite
270                          Ascension: Deckbuilding Game
769                                    Star Wars: Destiny
2285    The Lord of the Rings: The Fellowship of the R...
Name: name, dtype: object

In [28]:
get_recommendations('KLASK')

1853             Polarity
596                Quarto
1962              Gobblet
2488    Nine Men's Morris
98                 Blokus
1165        Blokus Trigon
2262               Gemblo
2020                Pylos
1982         StreetSoccer
772                 DVONN
Name: name, dtype: object

In [ ]:
def get_recommendations(name, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[name]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:21]

    # Get the movie indices
    game_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return game_plus_desc_df['name'].iloc[game_indices]

In [85]:
idx2 = indices['Ticket to Ride']
idx2

5

In [87]:
list(enumerate(cosine_sim[idx2]))

[(0, 0.022844052252551046),
 (1, 0.007756908303098398),
 (2, 0.049075930378832545),
 (3, 0.07519311765891161),
 (4, 0.02518668700226861),
 (5, 0.9999999999999998),
 (6, 0.003372168741293425),
 (7, 0.039642104761288294),
 (8, 0.02786281997892385),
 (9, 0.03585078707927814),
 (10, 0.034455011679876545),
 (11, 0.02504828031203426),
 (12, 0.4893306717860308),
 (13, 0.023424086050989685),
 (14, 0.0194501459554339),
 (15, 0.052347627904551414),
 (16, 0.036816352436642684),
 (17, 0.028838686772290987),
 (18, 0.030927852340619722),
 (19, 0.030565937702067038),
 (20, 0.013134772538111234),
 (21, 0.022521312987781872),
 (22, 0.04581102205810602),
 (23, 0.041704009607742745),
 (24, 0.03923744830524012),
 (25, 0.01772207003880149),
 (26, 0.016846283924809725),
 (27, 0.021868882464056195),
 (28, 0.03799950694424176),
 (29, 0.04913360667317732),
 (30, 0.02208501294559657),
 (31, 0.0035712251188834924),
 (32, 0.030697986762991115),
 (33, 0.04368589810065134),
 (34, 0.04395341605934839),
 (35, 0.00831

In [88]:
sim_scores2 = list(enumerate(cosine_sim[idx2]))

In [89]:
sim_scores2 = sorted(sim_scores2, key=lambda x: x[1], reverse=True)
sim_scores2

[(5, 0.9999999999999998),
 (681, 0.6013216719838244),
 (739, 0.5005092584474959),
 (12, 0.4893306717860308),
 (745, 0.4884404678600256),
 (318, 0.48253554374288454),
 (666, 0.44546677149657127),
 (2403, 0.43836237181925325),
 (809, 0.4122844584684699),
 (1253, 0.4055017077706708),
 (665, 0.404762626350347),
 (1272, 0.3999306059252505),
 (851, 0.352267762417433),
 (864, 0.34143996968632495),
 (1487, 0.3326938777298009),
 (2259, 0.3307510360995561),
 (1967, 0.284254443815856),
 (2862, 0.2825613098493347),
 (280, 0.2737829220960635),
 (364, 0.188937179687025),
 (2234, 0.1853596076240448),
 (2015, 0.15067655762231183),
 (2175, 0.1485636427210424),
 (141, 0.14059012350077582),
 (623, 0.11449062852630322),
 (2955, 0.11426073110963007),
 (1747, 0.10993973581357167),
 (2462, 0.10893781780358336),
 (1844, 0.10541472686189236),
 (737, 0.10538125963739838),
 (795, 0.10467306616435783),
 (2379, 0.10088502244361051),
 (1175, 0.09989912517540254),
 (434, 0.09736088959887268),
 (170, 0.09712576250438

In [90]:
sim_scores2 = sim_scores2[1:21]
sim_scores2

[(681, 0.6013216719838244),
 (739, 0.5005092584474959),
 (12, 0.4893306717860308),
 (745, 0.4884404678600256),
 (318, 0.48253554374288454),
 (666, 0.44546677149657127),
 (2403, 0.43836237181925325),
 (809, 0.4122844584684699),
 (1253, 0.4055017077706708),
 (665, 0.404762626350347),
 (1272, 0.3999306059252505),
 (851, 0.352267762417433),
 (864, 0.34143996968632495),
 (1487, 0.3326938777298009),
 (2259, 0.3307510360995561),
 (1967, 0.284254443815856),
 (2862, 0.2825613098493347),
 (280, 0.2737829220960635),
 (364, 0.188937179687025),
 (2234, 0.1853596076240448)]

In [91]:
game_indices2 = [i[0] for i in sim_scores2]
game_indices2

[681,
 739,
 12,
 745,
 318,
 666,
 2403,
 809,
 1253,
 665,
 1272,
 851,
 864,
 1487,
 2259,
 1967,
 2862,
 280,
 364,
 2234]

In [92]:
game_plus_desc_df['name'].iloc[game_indices2]

681                      Ticket to Ride: 10th Anniversary
739                           Ticket to Ride: Switzerland
12                                 Ticket to Ride: Europe
745                           Ticket to Ride: Europa 1912
318                              Ticket to Ride: USA 1910
666     Ticket to Ride Map Collection: Volume 2 – Indi...
2403                 Ticket to Ride: First Journey (U.S.)
809     Ticket to Ride Map Collection: Volume 5 – Unit...
1253                        Ticket to Ride: Rails & Sails
665     Ticket to Ride Map Collection: Volume 1 – Team...
1272    Ticket to Ride Map Collection: Volume 3 – The ...
851                         Ticket to Ride: The Card Game
864                              Ticket to Ride: New York
1487    Ticket to Ride Map Collection: Volume 4 – Nede...
2259                               Ticket to Ride: London
1967                       Ticket to Ride: Alvin & Dexter
2862    Ticket to Ride Map Collection: Volume 6 – Fran...
280           

In [29]:
ttr = get_recommendations('Ticket to Ride')

In [30]:
ttr

681                      Ticket to Ride: 10th Anniversary
739                           Ticket to Ride: Switzerland
12                                 Ticket to Ride: Europe
745                           Ticket to Ride: Europa 1912
318                              Ticket to Ride: USA 1910
666     Ticket to Ride Map Collection: Volume 2 – Indi...
2403                 Ticket to Ride: First Journey (U.S.)
809     Ticket to Ride Map Collection: Volume 5 – Unit...
1253                        Ticket to Ride: Rails & Sails
665     Ticket to Ride Map Collection: Volume 1 – Team...
Name: name, dtype: object

In [31]:
type(ttr)

pandas.core.series.Series

In [35]:
ranks = np.arange(1,11,1)
ranks

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
ttr_dict = {"Rank" : ranks, "Game" : ttr}

In [69]:
ttr_dict

{'Rank': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 'Game': 681                      Ticket to Ride: 10th Anniversary
 739                           Ticket to Ride: Switzerland
 12                                 Ticket to Ride: Europe
 745                           Ticket to Ride: Europa 1912
 318                              Ticket to Ride: USA 1910
 666     Ticket to Ride Map Collection: Volume 2 – Indi...
 2403                 Ticket to Ride: First Journey (U.S.)
 809     Ticket to Ride Map Collection: Volume 5 – Unit...
 1253                        Ticket to Ride: Rails & Sails
 665     Ticket to Ride Map Collection: Volume 1 – Team...
 Name: name, dtype: object}

In [71]:
ttr_df = pd.DataFrame(ttr_dict).reset_index(drop = True)

In [72]:
ttr_df

Rank                                               Game
0     1                   Ticket to Ride: 10th Anniversary
1     2                        Ticket to Ride: Switzerland
2     3                             Ticket to Ride: Europe
3     4                        Ticket to Ride: Europa 1912
4     5                           Ticket to Ride: USA 1910
5     6  Ticket to Ride Map Collection: Volume 2 – Indi...
6     7               Ticket to Ride: First Journey (U.S.)
7     8  Ticket to Ride Map Collection: Volume 5 – Unit...
8     9                      Ticket to Ride: Rails & Sails
9    10  Ticket to Ride Map Collection: Volume 1 – Team...

In [78]:
klask = get_recommendations('KLASK')
klask_dict = {"Rank" : ranks, "Game" : klask}
klask_df = pd.DataFrame(klask_dict).reset_index(drop = True)
klask_df

Rank               Game
0     1           Polarity
1     2             Quarto
2     3            Gobblet
3     4  Nine Men's Morris
4     5             Blokus
5     6      Blokus Trigon
6     7             Gemblo
7     8              Pylos
8     9       StreetSoccer
9    10              DVONN

In [79]:
hp = get_recommendations('Harry Potter: Hogwarts Battle')
hp_dict = {"Rank" : ranks, "Game" : hp}
hp_df = pd.DataFrame(hp_dict).reset_index(drop = True)
hp_df

Rank                                               Game
0     1  Harry Potter: Hogwarts Battle – The Monster Bo...
1     2                     Harry Potter Trading Card Game
2     3             Legendary: A Marvel Deck Building Game
3     4  Legendary: A Marvel Deck Building Game – Villains
4     5                       DC Comics Deck-Building Game
5     6                                  Disney Villainous
6     7         DC Comics Deck-Building Game: Heroes Unite
7     8                       Ascension: Deckbuilding Game
8     9                                 Star Wars: Destiny
9    10  The Lord of the Rings: The Fellowship of the R...

In [80]:
idx3 = indices['Harry Potter: Hogwarts Battle']
idx3

304